# Conexão PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/erp_licencas
spring.datasource.username=postgres
spring.datasource.password=postgres

db.licencas.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres
db.licencas.username=postgres.bqsdhzokmskdmynbmvah
db.licencas.password=K9vT2xP7mQ4zL8

db.oficial.url=jdbc:postgresql://localhost:5432/erp_oficial
db.oficial.username=postgres
db.oficial.password=postgres

spring.main.web-application-type=none
logging.level.root=WARN
logging.level.main=INFO